### ISSUE TITLE
pkg create for ament_python

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2cli#125]
There is currently no support for `ament_python` in `ros2 pkg create`. It defaults to `ament_cmake`, but there is no automated way to create python packages.

**Comment by db118** [comment]
First time contributing to open source and would love to take this issue. Could you possibly point me in the right direction in terms of running the project and testing.

**Comment by fkromer** [comment]
Probably helpful: [branch of ros2/examples with minimal python package](https://github.com/fkromer/examples/tree/minimal_python_package/rclpy/packages/minimal_package) in draft state.

**Comment by fkromer** [comment]
Probably relevant: [ROS 2 metapackages/variants support](https://github.com/ros2/ros2/issues/408)

**Comment by Karsten1987** [comment]
@db118 thanks for helping out. 

In general, you should be able to have ROS2 installed (either from source or binary) and then checkout this `ros2cli` repository in an overlay workspace.
Once that's done, you only have to compile your local `ros2pkg` package in your overlay workspace, which speeds up compile time. 
https://github.com/ros2/ros2/wiki/Colcon-Tutorial#create-an-overlay

I would recommend you have a look on how the two current build types are implemented (`ament_cmake` and `cmake`) and then proceed similarly for python. 
You can check with `colcon test` that all tests are run correctly and the linters are happy.

Once you are in a state of opening a PR, we are happy to review and run the build farm for you.
