### ISSUE TITLE
ros2 topic fail to echo PointCloud2 msg

### ISSUE THREAD

**Issue by yechun1** [ros2/ros2cli#127]
When I try to use big data message by python code such as Camera Image or PointCloud2 on ROS2, I found the performance is terrible.
Problem:
    Launch ros2_intel_realsense 2 by realsense_ros2_camera, and subscribe “/camera/depth/color/points” by “ros2 topic echo /camera/depth/color/points”. It will cost dozens of seconds to print out the PointCloud2 (640x480) data. On ros 1, rostopic shows data immediately.

Then I have wrote test code rttest_sample 2 to publish PointCloud2 on topic /rttest_sample. the result is:
Set data size as 64x48, “ros2 topic echo /rttest_sample” works.
Set data size as 640x48, “ros2 topic echo /rttest_sample” cost ~10s.
Set data size as 640x480, “ros2 topic echo /rttest_sample” cost more than 60s.

Issue discussing here: https://discourse.ros.org/t/image-and-pointcloud2-performance-on-ros2/5391

**Comment by yechun1** [comment]
PR https://github.com/ros2/ros2cli/pull/126 to fix this issue, please help review.

**Comment by mikaelarguedas** [comment]
Fixed by #126 , thanks @yechun1 for the fix
