### ISSUE TITLE
pyyaml dependency in ros2 topic echo

### ISSUE THREAD

**Issue by dhood** [ros2/ros2cli#17]
I didn't have `pyyaml` installed and got this error:

```
$ ros2 run demos_nodes_cpp listener
Failed to load entry point 'echo': No module named 'yaml'
```

I am adding `python3 -m pip install pyyaml` to the installation instructions, but I noticed it's not listed in the setup.py for `ros2topic` where I think it should be. Is that correct?

**Comment by Kukanani** [comment]
There's also `apt install python3-yaml`, which appears to satisfy the requirement as well.

I'm experiencing similar behavior on Windows, and I think I may need to use the `pip` install.

**Comment by mikaelarguedas** [comment]
> I'm experiencing similar behavior on Windows, and I think I may need to use the pip install

:+1: we should use the apt version on linux and the pip version on the other platforms

**Comment by dirk-thomas** [comment]
Added to https://github.com/ros2/ros2cli/pull/15/commits/41d411e93ed09b6742e60e5420fbfd86d66d2bbb

**Comment by dhood** [comment]
How come it doesn't also belong in the setup.py?

**Comment by dirk-thomas** [comment]
The manifest contains the dependency information. We don't have to duplicate them into the setup.py file.

**Comment by wjwwood** [comment]
> The manifest contains the dependency information. We don't have to duplicate them into the setup.py file.

There are things that are not provided by pip (like `rclpy`) but it doesn't hurt to put things into the `setup.py` which can be. But for packages which only have other python dependencies, it would be good to have a functional `setup.py`. So I don't agree with this as a general rule.

**Comment by dhood** [comment]
Seems especially strange that the setup.py currently lists `ros2cli` but not `pyyaml`.

Updating the instructions to install pyyaml from pip on windows and osx and python3-yaml from apt for linux. https://github.com/ros2/ci/pull/89 does the same for CI jobs
