### ISSUE TITLE
[ros2node] info requires fully qualified node name

### ISSUE THREAD

**Issue by sloretz** [ros2/ros2cli#181]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu bionic arm64
- Installation type:
  -  packaging job 
- Version or commit hash:
  - https://ci.ros2.org/view/packaging/job/packaging_linux-aarch64/649/
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

1. Launch a hidden node
   ```
   ros2 daemon start
   ```
1. Try to get info on the node using a fully qualified nod ename
   ```
   ros2 node info /_ros2cli_node_daemon_0
   ```
1. Try to get info on the node using a non fully qualified node name
   ```
   ros2 node info _ros2cli_node_daemon_0
   ```

#### Expected behavior

Both commands would list the info about the node

#### Actual behavior

The non-fully qualified version can't find the node.

```bash 
$ ros2 node info /_ros2cli_node_daemon_0
/_ros2cli_node_daemon_0
  Subscribers:

  Publishers:
    /parameter_events: rcl_interfaces/ParameterEvent
  Services:
    /_ros2cli_node_daemon_0/describe_parameters: rcl_interfaces/DescribeParameters
    /_ros2cli_node_daemon_0/get_parameter_types: rcl_interfaces/GetParameterTypes
    /_ros2cli_node_daemon_0/get_parameters: rcl_interfaces/GetParameters
    /_ros2cli_node_daemon_0/list_parameters: rcl_interfaces/ListParameters
    /_ros2cli_node_daemon_0/set_parameters: rcl_interfaces/SetParameters
    /_ros2cli_node_daemon_0/set_parameters_atomically: rcl_interfaces/SetParametersAtomically
$ ros2 node info _ros2cli_node_daemon_0
Unable to find node '_ros2cli_node_daemon_0'
```

**Comment by nuclearsandwich** [comment]
Double checking in https://github.com/ros2/ros2cli/pull/179#issuecomment-447307530 that this wasn't intentionally omitted from that change for some reason.

**Comment by sloretz** [comment]
> Double checking in #179 (comment) that this wasn't intentionally omitted from that change for some reason.

This issue was discovered after #179 was merged

**Comment by Karsten1987** [comment]
This was my bad. I should have checked for all the other existing verbs as
well.
