### ISSUE TITLE
Add a command to list all of the executables in a pkg

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2cli#21]
Currently, the `ros2 pkg` command has a way to list all packages, but not a way to list all executables that are available in a package.  I think it would be a good idea to be able to list all of the executables to make it easier for the user to find that list.

**Comment by mikaelarguedas** [comment]
:+1:
the workaround being to use the autocomplete provided by ros2 run given that people want to have a list of executable mostly to run them

**Comment by dirk-thomas** [comment]
See #23.
