### ISSUE TITLE
ros2 lifecycle get always shows state of all nodes even when selecting one by name

### ISSUE THREAD

**Issue by ralph-lange** [ros2/ros2cli#233]
## Bug report

When calling ros2 lifecycle get /nodename, the state of _all_ nodes is shown. Expected behavior is that only the state of the selected node is shown.

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Crystal from binary, Pre-Dashing from source
- Version or commit hash:
  - 1766de05961a7a08a77f446a22fca0abdd6d0552
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

```
[...]:~/ros2_dashing_ws$ ros2 lifecycle get
/damped_pendulum/damped_pendulum: inactive [2]
/transport_delay/transport_delay: unconfigured [1]
[...]:~/ros2_dashing_ws$ ros2 lifecycle get /damped_pendulum/damped_pendulum 
inactive [2]
unconfigured [1]
[...]:~/ros2_dashing_ws$ 
```

#### Expected behavior
Only the state of the selected node is shown.

#### Actual behavior
States of all nodes are shown - without names.

**Comment by ralph-lange** [comment]
@Karsten1987 See https://github.com/ros2/ros2cli/issues/233 for the issue with the two (or more) output lines with `ros2 lifecycle get /nodename`

**Comment by dirk-thomas** [comment]
Currently also all states are being queried even if only a specific node is requested: https://github.com/ros2/ros2cli/blob/1766de05961a7a08a77f446a22fca0abdd6d0552/ros2lifecycle/ros2lifecycle/verb/get.py#L52
