### ISSUE TITLE
Failed to load entry point

### ISSUE THREAD

**Issue by rosesue** [ros2/ros2cli#236]
- Operating System:
  - Ubuntu 16.04
- Installation type:
  - from source
- Version or commit hash:
  - commit 83f623a7f51c1ad4cda961267ebce0bc919be2cb
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
I build the ros2cli with the latest commit above. It reported errors when I ran "ros2 -h".
Error message is:
Failed to load entry point 'launch': invalid syntax (__init__.py, line 60)
Failed to load entry point 'stop': invalid syntax (node.py, line 123)
Failed to load entry point 'start': invalid syntax (node.py, line 123)
Failed to load entry point 'status': invalid syntax (node.py, line 123)
Failed to load entry point 'get': invalid syntax (node.py, line 123)
Failed to load entry point 'list': invalid syntax (node.py, line 123)
Failed to load entry point 'set': invalid syntax (node.py, line 123)
Failed to load entry point 'nodes': invalid syntax (node.py, line 123)
Failed to load entry point 'list': invalid syntax (node.py, line 123)
Failed to load entry point 'info': invalid syntax (node.py, line 123)
Failed to load entry point 'get': invalid syntax (node.py, line 123)
Failed to load entry point 'delete': invalid syntax (node.py, line 123)
Failed to load entry point 'list': invalid syntax (node.py, line 123)
Failed to load entry point 'set': invalid syntax (node.py, line 123)
Failed to load entry point 'generate_policy': invalid syntax (node.py, line 123)
Failed to load entry point 'call': invalid syntax (node.py, line 123)
Failed to load entry point 'list': invalid syntax (node.py, line 123)
Failed to load entry point 'delay': invalid syntax (node.py, line 123)
Failed to load entry point 'pub': invalid syntax (node.py, line 123)
Failed to load entry point 'list': invalid syntax (node.py, line 123)
Failed to load entry point 'echo': invalid syntax (node.py, line 123)
Failed to load entry point 'info': invalid syntax (node.py, line 123)
Failed to load entry point 'hz': invalid syntax (node.py, line 123)

**Comment by dirk-thomas** [comment]
You are trying to use the master branch of the repository on Ubuntu 16.04 which is not a supported combination. The master branch contains the code which will be released as ROS 2 Dashing which only targets Ubuntu 18.04 and requires a newer Python version than you have on 16.04 (hence the syntax errors).
