### ISSUE TITLE
ros2 param list --include-hidden-nodes does not return

### ISSUE THREAD

**Issue by jacobperron** [ros2/ros2cli#246]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Debian packages
- Version or commit hash:
  - 0.7.3
- DDS implementation:
  - Fast-RTPS and Connext (did not try OpenSplice)
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

```
ros2 param list --include-hidden-nodes
```

#### Expected behavior

Prints a list of parameters for any active nodes (including hidden nodes) and returns successfully.

#### Actual behavior

Nothing prints and the command never returns.

#### Additional information

It doesn't seem to matter if there are zero or more nodes, hidden or not running.

**Comment by dirk-thomas** [comment]
The hidden node causing this to fail is the daemon. By default the Python node starts a parameter server but the daemon never spins. PR incoming...
