### ISSUE TITLE
Argument completion doesn't work with Xenial python3-argcomplete installed

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2cli#25]
It does work if we install argcomplete from pip.  It is probably worthwhile to explore why this is and if we can make it work with the Xenial argcomplete.

**Comment by dhood** [comment]
did you re-source the setup file after installing python3-argcomplete? The argcomplete only gets registered when the setup file is sourced.

So, perhaps you didn't re-source it after installing python3-argcomplete, but you *did* re-source it after installing from pip, and that explains the difference in behaviour?

**Comment by clalancette** [comment]
I think I sourced it both times, but I'd have to go back and double-check to be 100% sure.

**Comment by dirk-thomas** [comment]
Please see #26.
