### ISSUE TITLE
ros2 srv show doesn't support <pkg>/srv/<servicename>

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2cli#257]
## Bug report

The output from `ros2 service list -t` shows something like:

```
/add_two_ints [example_interfaces/srv/AddTwoInts]
```

However, if you try to show that service type with `ros2 srv show example_interfaces/srv/AddTwoInts`, you get an error

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - eb5d2b79fabbd3f4cf888e0302f7841589acb79b
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

In terminal 1:
```
ros2 run demo_nodes_cpp add_two_ints_server
```

In terminal 2:
```
ros2 service list -t  # Among other things, shows /add_two_ints [example_interfaces/srv/AddTwoInts]
ros2 srv show example_interfaces/srv/AddTwoInts
```

#### Expected behavior
Outputs:
```
int64 a
int64 b
---
int64 sum
```

#### Actual behavior
Outputs:
```
The passed service type is invalid
```

#### Additional information

Running `ros2 srv show example_interfaces/AddTwoInts` does the correct thing.

**Comment by jacobperron** [comment]
I believe the same is true for `ros2 msg show` and `ros2 action show`.
