### ISSUE TITLE
Unable to list parameters for hidden nodes

### ISSUE THREAD

**Issue by jacobperron** [ros2/ros2cli#267]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - 9f6c337a4789a8a67ffe57f3b6f563ae4ada9623
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Start a hidden node:
```
ros2 run demo_nodes_cpp talker __node:=_foo
```

List parameters including hidden nodes:
```
ros2 param list --include-hidden-nodes
```

#### Expected behavior

We see the following output:
```
/_foo:
  use_sim_time
```

#### Actual behavior

We see no output.

**Comment by jubeira** [comment]
This is fixed in Dashing binaries for Ubuntu 18 :+1:
