### ISSUE TITLE
Expose QoS policies to `ros2 topic echo` (like in `pub`)

### ISSUE THREAD

**Issue by emersonknapp** [ros2/ros2cli#281]
#### Feature description
`ros2 topic pub` now exposes a few QoS settings to the commandline (https://github.com/ros2/ros2cli/pull/238). These would be equally handy on `ros2 topic echo`, for example for echoing latched (durability=TRANSIENT_LOCAL) values.

#### Implementation considerations
This should be straightforward reuse of the pattern from `pub`

**Comment by mickeyouyou** [comment]
why can not use in dashing version ?
