### ISSUE TITLE
[ros2topic] ros2 topic list does not have a -v/--verbose option

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2cli#347]
#### Feature description

In ROS 1 there was a `-v` option which listed out data like this (from https://wiki.ros.org/ROS/Tutorials/UnderstandingTopics#Using_rostopic_list):

```
Published topics:
 * /turtle1/color_sensor [turtlesim/Color] 1 publisher
 * /turtle1/cmd_vel [geometry_msgs/Twist] 1 publisher
 * /rosout [rosgraph_msgs/Log] 2 publishers
 * /rosout_agg [rosgraph_msgs/Log] 1 publisher
 * /turtle1/pose [turtlesim/Pose] 1 publisher

Subscribed topics:
 * /turtle1/cmd_vel [geometry_msgs/Twist] 1 subscriber
 * /rosout [rosgraph_msgs/Log] 1 subscriber
```

This doesn't exist in ROS 2 yet, and it would be useful (for that tutorial and in general) for `ros2 topic list` as well.

**Comment by evshary** [comment]
I study the issue recently. I'd like to work on it.

**Comment by matthews-jca** [comment]
Going through some "good first issues" and noted that this issue appears to have been fixed and merged.

**Comment by clalancette** [comment]
Yep, very good point.  I'm going to close this out.
