### ISSUE TITLE
[ros2interface] does not allow input from stdin for `show`

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2cli#349]
#### Feature description

In this ROS 1 tutorial (https://wiki.ros.org/ROS/Tutorials/UnderstandingTopics#Using_rostopic_hz) there is a shell one-liner:

```
$ rostopic type /turtle1/cmd_vel | rosmsg show
```

Which then shows the structure of the topic type for the `/turtle1/cmd_vel`.

It would be nice to have this ability in the ROS 2 `ros2 interface show` command line tool too.

**Comment by sharminramli** [comment]
I'd like to work on this, but it looks like ros2msg was deprecated in #363. Can I go ahead and look into implementing this feature in ros2interface if it's still relevant?

**Comment by jacobperron** [comment]
@sharminramli Thanks for volunteering to look into this!
Correct, ros2msg is deprecated, but I believe the feature is still relevant to ros2interface. I'll change the title and description of this ticket accordingly.

**Comment by sharminramli** [comment]
this can probably be closed?

**Comment by clalancette** [comment]
Yeah, good call.  Closing this out.
