### ISSUE TITLE
Auto completion not working on OSX 

### ISSUE THREAD

**Issue by claireyywang** [ros2/ros2cli#397]
## Bug report

**Required Info:**

- Operating System:
  - OSX Mojave 
- Installation type:
  - From source 
- Version or commit hash:
  - Eloquent 
- DDS implementation:
  - N/A 
- Client library (if applicable):
  - N/A 

#### Steps to reproduce issue

1. source the ROS2 environment 
2. check ``argcomplete`` python package is installed
3. type in any ros2 commands and try tab-completion
```
ros2 run demo_
```
or 
```
ros2 topic p
```
#### Expected behavior
auto complete the verb or package name
#### Actual behavior
no auto-completion behaviour, require manual typing full verb/name

**Comment by dirk-thomas** [comment]
In this case the executable `register-python-argcomplete` was not available. Uninstalling and reinstalling `argcomplete` fixed that problem and now completion works.
