### ISSUE TITLE
test_fibonacci_info[rmw_connext_cpp] (test_cli.TestROS2ActionCLI) failing in nightly builds

### ISSUE THREAD

**Issue by emersonknapp** [ros2/ros2cli#450]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  - master
- DDS implementation:
  - rmw_connext_cpp
- Client library (if applicable):
  - N/A

The nightly builds are unstable because of the failing test `test_fibonacci_info[rmw_connext_cpp] (test_cli.TestROS2ActionCLI)`

Latest results
https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1451/testReport/junit/ros2action.test/test_cli/test_cli/
https://ci.ros2.org/view/nightly/job/nightly_linux_release/1436/testReport/junit/ros2action.test/test_cli/test_cli/

#### Steps to reproduce issue
N/A

#### Expected behavior

Tests pass

#### Actual behavior

Test fails

**Comment by clalancette** [comment]
I believe that this was fixed before Foxy.  I haven't seen it in the buildfarmer logs for a few weeks now, at least.  I'm going to go ahead and close this, but feel free to reopen if you think this is still a problem.
