### ISSUE TITLE
Add a warning in ros2node when dealing with non-uniquely-named nodes

### ISSUE THREAD

**Issue by emersonknapp** [ros2/ros2cli#453]
## Feature request

Related to https://github.com/ros2/ros2cli/issues/279 - but a much simpler feature request

* When running `ros2 node list`, add a top level warning and a small note next to all nodes that share a name, e.g.

```
$ ros2 node list
# WARNING: There are nodes in the graph that share a name - it is recommended that you use namespaces or different names to differentiate nodes
/talker (not uniquely named)
/listener
/talker (not uniquely named)
```

* When running `ros2 node info`, add a note that you are receiving information about only one node with the given name, if multiple are present, e.g.

```
$ ros2 node info /talker
# WARNING: there is more than one node found that has the name /talker, you are seeing information about only one of them. It is not guaranteed that you will see information about the same node every time
etc...
```

This should help make the non-unique situation more obvious, even though it doesn't fix anything.

#### Implementation considerations
We should already have all the information we need, a sort and pass over the node list should do for both cases.

**Comment by hidmic** [comment]
@emersonknapp as far as I can see, this issue has been fully addressed. I'll close it.
