### ISSUE TITLE
Feature Request - ros2 topic echo --once

### ISSUE THREAD

**Issue by craigh92** [ros2/ros2cli#529]
## Feature request

Add an option `--once` to the `ros2 topic echo` command, that will cause the command to exit after it has received and printed one message. Also add a `--timeout ` option that will cause the command to exit if a certain period of time has elapsed.

#### Feature description

If messages are being published representing the state of the system, then the `ros2 topic echo` is useful for querying the current state. The last message is often all that the user is interested in. `ros2 topic echo --qos-durability=transient_local --once` will be a quick way of sending a "Get" command, that gets the current value of something in the system.

It will also be useful for writing tests. e.g

```bash
source /opt/ros/eloquent/setup.bash
source ./install/setup.sh

#Launch all nodes in a background process
ros2 launch -a launch/my_launch.py &>ros_out_log &
pid=$!

#Test initial state of robot1
pos=$(ros2 topic echo --qos-durability=transient_local --once robot1/position msgs/PositionMsg)
    #test $pos...

#Send move command
ros2 service call robot1/move srvs/MoveSrv {x: 1, y: 2}

sleep 2

#Test new poistion of robot1
pos=$(ros2 topic echo --qos-durability=transient_local --once robot1/position msgs/PositionMsg)
    #test $pos...

#Shutdown all nodes

kill -2 $pid

echo "waiting for nodes to shutdown..."

nodes=$(ros2 node list)
numnodes=$(echo $nodes | wc -w)
while [[ $numnodes != 0 ]]; do
  nodes=$(ros2 node list)
  numnodes=$(echo $nodes | wc -w)
  echo "$numnodes remaining"
  sleep 1
done

```

This is much easier than having to create subscribers, clients, etc in a python file and testing it that way.

#### Implementation considerations

This should be pretty easy to implement. Instead of `rclpy.spin(node)` [here](https://github.com/ros2/ros2cli/blob/f7bebe0f88e811104271758f038cef8abb5285d9/ros2topic/ros2topic/verb/echo.py#L117), replace with `rclpy.spin_untill_future_complete()` (which already has a timeout feature built into it), and then set the future as complete in the subscription callback.

I've made a start here: https://github.com/craigh92/ros2cli/commit/10e716dacfd838799a0510bbf67f45f87eff152c
I've not contributed before so I'm not sure if I'm using `parser.add_argument` correctly.

**Comment by craigh92** [comment]
@dirk-thomas How do I test my PR?

If I type `ros2 topic echo` it will call the code that was installed when I did a full ros installation.

Ideally, I don't want to break the main installation. Is there a way to run the CLI tools without installing them?

**Comment by clalancette** [comment]
You should be able to overlay them.  That is, make a workspace with your forked copy of `ros2cli`, build that, and then source `install/setup.bash` that is generated in that workspace.  You should now be able to use your versions of the commands.

**Comment by craigh92** [comment]
@clalancette Thanks fot your help. I have tried this, but even with a fresh fork that I have not changed, I get errors when I try to run the commands:

```
craig@craig-HP-EliteBook-8770w:~/Git/ws2$ ros2 topic -h
Failed to load entry point 'bw': No module named 'rclpy.topic_endpoint_info'
Failed to load entry point 'delay': No module named 'rclpy.topic_endpoint_info'
Failed to load entry point 'echo': No module named 'rclpy.topic_endpoint_info'
Failed to load entry point 'find': No module named 'rclpy.topic_endpoint_info'
Failed to load entry point 'hz': No module named 'rclpy.topic_endpoint_info'
Failed to load entry point 'info': No module named 'rclpy.topic_endpoint_info'
Failed to load entry point 'list': No module named 'rclpy.topic_endpoint_info'
Failed to load entry point 'pub': No module named 'rclpy.topic_endpoint_info'
Failed to load entry point 'type': No module named 'rclpy.topic_endpoint_info'
```

My directory structure looks like:
ws2
ws2/src
ws2/src/ros2cli (this is the cloned fork)
ws2/install

Do you know where I am going wrong? It seems to be something to do with missing `'rclpy.topic_endpoint_info`. Thanks.

**Comment by clalancette** [comment]
In this case, the likely problem is that your underlay is binary (I'm guessing Eloquent), but your overlay is brand-new (essentially post-Foxy).

You *may* be able to install Foxy in a 20.04 container and overlay it that way.  If that doesn't work, you'll have to build from source.

**Comment by craigh92** [comment]
> In this case, the likely problem is that your underlay is binary (I'm guessing Eloquent), but your overlay is brand-new (essentially post-Foxy).
> 
> You _may_ be able to install Foxy in a 20.04 container and overlay it that way. If that doesn't work, you'll have to build from source.

You're right. Upgrading to foxy has fixed the issue. I have now been able to test my PR and it works, thank you :)

**Comment by mickeyouyou** [comment]
Is it enable in command `ros2 topic echo --qos-durability=transient_local `   option like --qos-durability=transient_local ?

**Comment by fujitatomoya** [comment]
reopen this in favor of https://github.com/ros2/ros2cli/pull/695
