### ISSUE TITLE
[ros2interface] Tests rely on `builtin_interfaces`

### ISSUE THREAD

**Issue by audrow** [ros2/ros2cli#541]
The tests in `ros2interface` use interface types defined in `builtin_interfaces` and effectively checks some of the interface definition's file contents.  This makes it possible for `ros2interface`'s tests to fail when changes are made to `builtin_interfaces`.

In #540 it was proposed to add interface definitions into `ros2interface`.  Doing so will allow `ros2interface` to better control the messages used in its tests and remove `ros2interface`'s dependency on `builtin_interfaces`.

**Comment by jacobperron** [comment]
It'd be good to fill out the ticket description to briefly describe what the issue is and optionally a proposed solution.
