### ISSUE TITLE
'test_topic_pub_once' test flaky

### ISSUE THREAD

**Issue by jacobperron** [ros2/ros2cli#552]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04 and macOS (Mojave)
- Installation type:
  - source
- Version or commit hash:
  - 95bfb056df795b6eef8bb73b165db31fcf2d867a

#### Steps to reproduce issue

See failing CI jobs, for example:

- https://ci.ros2.org/job/nightly_linux_repeated/1925/testReport/ros2topic.ros2topic.test/test_cli/test_cli/
- https://ci.ros2.org/job/nightly_linux-aarch64_repeated/1248/testReport/ros2topic.ros2topic.test/test_cli/test_cli/
- https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/2019/testReport/ros2topic.ros2topic.test/test_cli/test_cli/

#### Expected behavior

Tests pass

#### Actual behavior

Tests sometimes failing

#### Additional information

The tests are flaky; they do not occur every night. When they fail, it is not tied to one particular RMW implementation.

**Comment by cottsay** [comment]
This is back already, so clearly my change didn't fix it: http://build.ros2.org/job/Fci__nightly-debug_ubuntu_focal_amd64/170/testReport/junit/ros2topic.test/test_cli/test_cli/

**Comment by jacobperron** [comment]
I think this was actually fixed by the referenced PR (for master).

The Foxy CI failure should have been fixed the backport of this in https://github.com/ros2/ros2cli/pull/565.
