### ISSUE TITLE
Failed to load entry point 'list': libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by LoyVanBeek** [ros2/ros2cli#567]
Just upgraded my laptop from Ubuntu 18.04 with Eloquent to 20.04 with Foxy.
My workspace in `~/dev_ws` was set up when I was still on 18.04 w/ Eloquent and was untouched during the `do-release-upgrade`. 
Once on Foxy, I could not run `ros2 topic list` anymore, with this error:

```
ros2 topic list
Failed to load entry point 'list': libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
The C extension '/opt/ros/foxy/lib/python3.8/site-packages/rclpy/_rclpy.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Traceback (most recent call last):
  File "/opt/ros/foxy/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.9.7', 'console_scripts', 'ros2')()
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2cli/cli.py", line 39, in main
    add_subparsers_on_demand(
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 249, in add_subparsers_on_demand
    extension.add_arguments(
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2topic/command/topic.py", line 29, in add_arguments
    add_subparsers_on_demand(
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2cli/command/__init__.py", line 236, in add_subparsers_on_demand
    extension = command_extensions[name]
KeyError: 'list'
```

After just a bit too long of apt-removing packages, installing them again etc, I figured out that when I did not have `source /home/loy/dev_ws/install/local_setup.bash` in my `~/.bashrc`, it did actually work. 
I don't know the exact details, but `rm -rf ~/dev_ws/install && colcon build` did the trick to make it work again.

No issue anymore, but wanted to note this for any future readers. If there is a better place to document this if that is desired, please let me know. 

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  -  Binary install, `sudo apt install ros-foxy-desktop`
- Version or commit hash:
  - 0.9.2-1focal.20200911.235014 (according to `dpkg -s ros-foxy-desktop`)
- DDS implementation:
  - Not applicable
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
- Install Ubuntu 18.04
- Install ROS 2 Eloquent
- Create a workspace, build, compile it
- `sudo do-release-upgrade` to Ubuntu 20.04
- `sudo apt install ros-foxy-desktop`
- `ros2 topic list`

#### Expected behavior
See a list of topics:
```
/parameter_events
/rosout
```

#### Actual behavior
Command outputs
```
Failed to load entry point 'list': libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
The C extension '/opt/ros/foxy/lib/python3.8/site-packages/rclpy/_rclpy.cpython-38-x86_64-linux-gnu.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
```
#### Additional information
Can be resolved by deleting and re-creating `~/dev_ws/install` by 
```bash
cd ~/dev_ws
rm -rf install
colcon build
```

**Comment by clalancette** [comment]
The problem here isn't really ROS-specific.  Anything you build from source is likely to break across an OS upgrade; a lot of dependencies have probably upgraded and thus the libraries that the source built against probably doesn't exist anymore.

I'm going to close this issue out, since there really isn't anything we can do about it.  We *might* want to put something in the documentation, but again, since this isn't ROS-specific, it is not entirely clear to me that we should.  In any case, we can continue that conversation on ros2/ros2_documentation#875
