### ISSUE TITLE
Multiple ROS 2 daemon node names collide

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2cli#640]
If you run `ros2 topic list` on two separate machines on the network, each of them starts up a copy of the ROS 2 daemon.  Unfortunately, the two daemons have exactly the same node name, namely `_ros2cli_daemon_0`.  This becomes a problem when you get a full node listing:

```
$ ros2 node list -a
WARNING: Be aware that are nodes in the graph that share an exact name, this can have unintended side effects.
/_ros2cli_daemon_0
/_ros2cli_daemon_0
```

It turns out to be relatively benign, since most users don't use the `-a` flag, but it would still be nicer to have these be unique if possible.

The code that produces this name is in two places:

* https://github.com/ros2/ros2cli/blob/edbc1600aa161845c58138bc18907bd873670a54/ros2cli/ros2cli/daemon/__init__.py#L56 (where the node suffix is produced from the domain ID)
* https://github.com/ros2/ros2cli/blob/edbc1600aa161845c58138bc18907bd873670a54/ros2cli/ros2cli/node/__init__.py#L15 (where the hard-coded prefix is produced)

It might make sense to append some kind of UUID or MAC address or IP address to the daemon name to make sure that they are unique across the network.

**Comment by fujitatomoya** [comment]
I'd rather use UUID since we can bind the same network interface to container runtime.
