### ISSUE TITLE
ros2 param list doesn't work while rqt is running

### ISSUE THREAD

**Issue by Kaju-Bubanja** [ros2/ros2cli#662]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - ros2 master source checkout
- Version or commit hash:
  - 1f4a3aaf7b930830b3fa04773715bf93ea65693e
- DDS implementation:
  - rmw_fastrtps_cpp
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
When running `rqt` and then `ros2 param list` I get 
`Exception while calling service of node '/rqt_gui_py_node_6150': None`
#### Expected behavior
I would expect it to tell me what params there are
#### Actual behavior
I get following exception: `Exception while calling service of node '/rqt_gui_py_node_6150': None`
#### Additional information
The same happens for nodes that I have written, but it also happens after a complete reboot and just starting `rqt` and running `ros2 param list`. I confirmed that no other node is running and messing something up with `ros2 node list` which only reports `/rqt_gui_py_node_6150`
Rqt runs normal and shows it's only defined param which is use_sim_time which is unchecked in the GUI. When I click on my custom node I get: 
`[rqt_reconfigure]: Failed to retrieve parameters from node: asynchronous service call failed: the target node may not be spinning`
while not directly relevant to the issue it might be connected

**Comment by clalancette** [comment]
Same here; I cannot reproduce this issue on the latest ros2 code.

@Kaju-Bubanja Can you explain further about how you have rqt configured?  Maybe there is some plugin that we need loaded in order to see this issue.

**Comment by Kaju-Bubanja** [comment]
I will try to reproduce this week with the hash of ros2 you tried.

**Comment by Kaju-Bubanja** [comment]
Could not reproduce either.
