### ISSUE TITLE
Topic Info verbose doesn't show pub/sub queue depth

### ISSUE THREAD

**Issue by matthews-jca** [ros2/ros2cli#667]
#### Feature description
when running ros2 topic info with the --verbose nothing is exposed for the publisher/subscriber queue depths (when using keep last N)

Not sure if it's as simple as adding in the extra parameter https://github.com/ros2/rclpy/blob/691e4fbfcb4bd4cc2a01182a7dced3105a78200b/rclpy/rclpy/topic_endpoint_info.py#L32 or if this needs to be exposed at the C level first.

**Comment by matthews-jca** [comment]
As this is part of the qosprofile itself I believe the actual fix is just to add the qosprofile.depth https://github.com/ros2/rclpy/blob/691e4fbfcb4bd4cc2a01182a7dced3105a78200b/rclpy/rclpy/topic_endpoint_info.py#L169 correct? If so, I can get a PR up at the rclpy level.

**Comment by fujitatomoya** [comment]
@matthews-jca yes, i think that will do the all the trick.

**Comment by fujitatomoya** [comment]
@matthews-jca i just created https://github.com/ros2/rclpy/pull/849, it will be nice if you could help review on that :bow:

**Comment by matthews-jca** [comment]
Following up from https://github.com/ros2/rclpy/pull/849#issuecomment-970912206 being not shared across all RMWs, it's still super helpful and useful to get those settings when available. I know hand coding a per-rmw solution is unsustainable, but would a separate cli command be better here?

**Comment by clalancette** [comment]
This was fixed a long time ago, so closing this out.
