### ISSUE TITLE
Remove options that do not do anything from ros2component

### ISSUE THREAD

**Issue by jacobperron** [ros2/ros2cli#710]
This is not really a bug or a feature request. I just noticed that when we run `ros2 component types --help` we see the following options that have no affect on the operation of listing items in the ament index:

```
  --spin-time SPIN_TIME
                        Spin time in seconds to wait for discovery (only applies when not using an already running daemon)
  -s, --use-sim-time    Enable ROS simulation time
  --no-daemon           Do not spawn nor use an already running daemon
```

IMO, it would be better to remove those from the output to avoid any potential confusion.

**Comment by clalancette** [comment]
That turned out to be a 2-line fix; see https://github.com/ros2/ros2cli/pull/711 .
