### ISSUE TITLE
ros2 topic echo: No option to clear screen

### ISSUE THREAD

**Issue by ahemwe** [ros2/ros2cli#725]
#### Feature description

In ROS 1 `rostopic echo` has an option "-c"
`$ rostopic echo -c /topic_name`

Meaning:
_Clear the screen after each message is published. Cannot be used with -p._

See: http://wiki.ros.org/rostopic#rostopic_echo

This is very helpful when using a terminal session to monitor ros messages in a terminal.

In ROS 2 this option is not available as of now. I would highly appreciate if this could be implemented.

**Comment by torrhen** [comment]
Would require something like the `"\033[2J\033[;H"` ANSI control sequence prefixed for each message callback to clear display and reposition cursor.

No `-p` argument in this case, but `--csv` looks similar. Are they equivalent given this context?
