### ISSUE TITLE
ros2 cli wrong help message for argument

### ISSUE THREAD

**Issue by omertal88** [ros2/ros2cli#755]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```
ros2 component load -h
```

#### Expected behavior
`container_node_name   Container node name to unload component from`
#### Actual behavior
`container_node_name   Container node name to load component to`
(please correct my grammer if needed).
#### Additional information

----

**Comment by clalancette** [comment]
Good call, see #756

**Comment by fujitatomoya** [comment]
@clalancette do we want to backport this to humble/galactic/foxy?

**Comment by clalancette** [comment]
> @clalancette do we want to backport this to humble/galactic/foxy?

Yeah, good call.

**Comment by clalancette** [comment]
@Mergifyio backport humble galactic foxy
