### ISSUE TITLE
how to debug launch file?

### ISSUE THREAD

**Issue by HaoLiuHust** [ros2/ros2cli#803]
as we know, we can use ros2 launch pkg_name xx.py to execute a launch file. 
is there a way to debug a python launch file using vscode if I want to set breakpoints in the launch file?

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
