### ISSUE TITLE
The `ros2 param dump` documentation (with `-h`) seems to be outdated.

### ISSUE THREAD

**Issue by mmmarinho** [ros2/ros2cli#836]
## Documentation mismatch report

The `ros2 param dump` documentation (with `-h`) seems to be outdated.

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - binaries
- Version or commit hash:
  - N/A
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce the issue

```console
ros2 param dump -h
```
#### Expected behavior

As far as I could tell from using the tool, the code, and the documentation about it, `ros2 param dump` no longer creates a file. Hence, we might benefit from a description of the current behavior of the tool, similar to the description in https://docs.ros.org/en/rolling/How-To-Guides/Using-ros2-param.html#ros2-param-dump

```console
Print out all of the parameters on a particular node in a YAML file format.
```
#### Actual behavior

https://github.com/ros2/ros2cli/blob/960962a142323c7a13c4ddef3a7e661d77905f93/ros2param/ros2param/verb/dump.py#L31-L32

```console
Dump the parameters of a node to a yaml file
```

**Comment by fujitatomoya** [comment]
backport to iron: https://github.com/ros2/ros2cli/pull/840
