### ISSUE TITLE
:farmer: Tests failing due to new FastDDS change

### ISSUE THREAD

**Issue by Crola1702** [ros2/ros2cli#861]
## Bug report

- Operating System:
  - Linux, aarch64, RHEL
- Installation type:
  - Source
- Version or commit hash:
  - Rolling

#### Steps to reproduce issue
1. Run a Linux build in ci.ros2.org
2. See test failures

#### Expected behavior

Test should not fail

#### Actual behavior

Test failing

#### Additional information

Reference build: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/

<details>
<summary>
Also happening in:
</summary>

* nightly_linux_repeated
* nightly_linux_release
* nightly_linux_debug
* nightly_linux-rhel_repeated
* nightly_linux-rhel_debug
* nightly_linux-aarch64_repeated
* nightly_linux-aarch64_release
* nightly_linux-aarch64_debug
* Rci__nightly-fastrtps_ubuntu_jammy_amd64
* Rci__nightly-fastrtps-dynamic_ubuntu_jammy_amd64
* Rci__nightly-debug_ubuntu_jammy_amd64

</details>

<details>
<summary>
Test regressions:
</summary>

* [ros2service.ros2service.test.test_cli.test_cli](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2service.ros2service.test/test_cli/test_cli/)
* [ros2service.ros2service.test.test_echo.test_echo](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2service.ros2service.test/test_echo/test_echo/)
* [ros2action.ros2action.test.test_cli.test_cli](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2action.ros2action.test/test_cli/test_cli/)
* [ros2param.ros2param.test.test_verb_dump.test_verb_dump](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2param.ros2param.test/test_verb_dump/test_verb_dump/)
* [ros2param.ros2param.test.test_verb_list.test_verb_list](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2param.ros2param.test/test_verb_list/test_verb_list/)
* [ros2param.ros2param.test.test_verb_load.test_verb_load](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2param.ros2param.test/test_verb_load/test_verb_load/)
* [ros2topic.ros2topic.test.test_cli.test_cli](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2topic.ros2topic.test/test_cli/test_cli/)
* [ros2topic.ros2topic.test.test_echo_pub.test_echo_pub](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2topic.ros2topic.test/test_echo_pub/test_echo_pub/)
* [ros2lifecycle.ros2lifecycle.test.test_cli.test_cli](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/junit/ros2lifecycle.ros2lifecycle.test/test_cli/test_cli/)

</details>

<details>
<summary>
Log output:
</summary>

```
AIL: test_echo_pub.TestROS2TopicEchoPub.test_echo_once
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins-agent/workspace/nightly_linux_debug/ws/install/launch_testing/lib/python3.10/site-packages/launch_testing/markers.py", line 57, in _wrapper
    return func(self, *args, **kwargs)
  File "/home/jenkins-agent/workspace/nightly_linux_debug/ws/src/ros2/ros2cli/ros2topic/test/test_echo_pub.py", line 504, in test_echo_once
    assert launch_testing.tools.expect_output(
AssertionError: assert False
 +  where False = <function expect_output at 0x7fef8c9a6950>(expected_lines=['data: hello', '---'], text='\x1b[37;1m2023-10-19 06:47:27.337 \x1b[31;1m[\x1b[37;1mRTPS_PARTICIPANT\x1b[31;1m Error] \x1b[37mCould not create the...create the specified receiver resource\x1b[34;1m -> Function \x1b[36mcreateReceiverResources\x1b[m\ndata: hello\n---\n', strict=True)
 +    where <function expect_output at 0x7fef8c9a6950> = <module 'launch_testing.tools' from '/home/jenkins-agent/workspace/nightly_linux_debug/ws/install/launch_testing/lib/python3.10/site-packages/launch_testing/tools/__init__.py'>.expect_output
 +      where <module 'launch_testing.tools' from '/home/jenkins-agent/workspace/nightly_linux_debug/ws/install/launch_testing/lib/python3.10/site-packages/launch_testing/tools/__init__.py'> = launch_testing.tools
 +    and   '\x1b[37;1m2023-10-19 06:47:27.337 \x1b[31;1m[\x1b[37;1mRTPS_PARTICIPANT\x1b[31;1m Error] \x1b[37mCould not create the...create the specified receiver resource\x1b[34;1m -> Function \x1b[36mcreateReceiverResources\x1b[m\ndata: hello\n---\n' = <launch_testing.tools.process.ProcessProxy object at 0x7fef82877e20>.output
```

</details>

---

The only change to the code between yesterday and today was: https://github.com/eProsima/Fast-DDS/pull/3936. So this is probably the failure cause

<details>

```diff
   eProsima/Fast-DDS:
     type: git
     url: https://github.com/eProsima/Fast-DDS.git
-    version: 38820e9fcf6256d3d121cd3273ecfe309cec0328
+    version: 6ffa92b47b9ab83759c531954e4fc22e4fa33442
   eProsima/foonathan_memory_vendor:
     type: git
     url: https://github.com/eProsima/foonathan_memory_vendor.git
```

</details>

Reproducing the problem: [![Build Status](https://ci.ros2.org/job/ci_linux-aarch64/14186/badge/icon)](https://ci.ros2.org/job/ci_linux-aarch64/14186/)

**Comment by fujitatomoya** [comment]
related to https://github.com/ros2/ros2/issues/1494

https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2837/testReport/ros2service.ros2service.test/test_cli/test_cli/

> text="\x1b[37;1m2023-10-19 05:53:28.041 \x1b[31;1m[\x1b[37;1mRTPS_PARTICIPANT\x1b[31;1m Error] \x1b[37mCould not create the...t16_value=0, uint16_value=0, int32_value=-1, uint32_value=0, int64_value=0, uint64_value=0, string_value='bazbar')\n\n", strict=True)

this error is the one reported to above issue.

fix is available here, https://github.com/eProsima/Fast-DDS/pull/3954
