### ISSUE TITLE
ros2 node can't be started

### ISSUE THREAD

**Issue by alittlechiled** [ros2/ros2cli#874]
I use the launch to start a node. 
![image](https://github.com/ros2/ros2cli/assets/108386043/9fdd649a-b169-4dff-b58f-26876887011f)

However, I can't find the node when I use the "ros2 node list" in my terminal.
![image](https://github.com/ros2/ros2cli/assets/108386043/ac79a4de-dee6-4696-aac4-2d0133716797)

this is my launch:
![image](https://github.com/ros2/ros2cli/assets/108386043/1d053620-6cc0-4912-be0f-eaf0147b7181)
this is my head file of the node code:
![image](https://github.com/ros2/ros2cli/assets/108386043/04b06029-e4d1-40ef-99a4-771ea8b2bdb5)
![image](https://github.com/ros2/ros2cli/assets/108386043/3dd31fde-9302-4b76-ac9b-bf404640452a)
this is my source file of the node code:
![058d58e68f029b1730b7b1d67bdb2cea](https://github.com/ros2/ros2cli/assets/108386043/45fb42db-dcf0-4121-b97e-62f18496664f)
![d36a2d5a8fb790e1e5eb5db88e573ef2](https://github.com/ros2/ros2cli/assets/108386043/108e368d-9561-4584-bcdb-50ef4d431151)
![6ddbda32257444c3a62711f2469bcb4f](https://github.com/ros2/ros2cli/assets/108386043/47de6785-76cd-4dc7-9daa-a2017d6bb18c)
![a4aae13c44ba7f4c364200428325004e](https://github.com/ros2/ros2cli/assets/108386043/58171ece-504e-40b2-b320-42d25d525d0f)

this is my cmake:
![7053d362d66ac513fb0b42f0d6ca3dea](https://github.com/ros2/ros2cli/assets/108386043/de774e17-97eb-43f6-8667-c8f110227873)

My file is shown below:
![a9b88ead53189b4ed7924fbc1f4eb8ae](https://github.com/ros2/ros2cli/assets/108386043/2e5ae56f-29bc-4765-8c5a-e7f8a7103e61)

When I found this bug, I checked all the naming issues.However, it didn't work.
I checked the Internet and found no solution...

My ubuntu is 20.04 and my ros is humble

**Comment by alittlechiled** [comment]
I solve the problem by changing the name of the namespace and function pack ......

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
