### ISSUE TITLE
New Flake 8 errors

### ISSUE THREAD

**Issue by sloretz** [ros2/ros2cli#92]
https://ci.ros2.org/job/ci_linux-aarch64/1426/testReport/

```
./ros2cli/plugin_system.py:63:5: F841 local variable 'e' is assigned to but never used
    except PluginException as e:
    ^

./ros2cli/plugin_system.py:68:5: F841 local variable 'e' is assigned to but never used
    except Exception as e:
    ^

./ros2cli/entry_points.py:86:9: F841 local variable 'e' is assigned to but never used
        except Exception as e:
        ^

3     F841 local variable 'e' is assigned to but never used

22 files checked
3 errors
```

**Comment by dirk-thomas** [comment]
See ros2/build_cop/issues/120.

**Comment by mikaelarguedas** [comment]
Duplicate of https://github.com/ros2/build_cop/issues/120#issuecomment-393310775 ?

**Comment by sloretz** [comment]
Ah, I searched the build_cop repo before opening this issue, but did not find that comment. I'll leave this open since an issue is easier to find.

**Comment by dirk-thomas** [comment]
The discussion on the upstream ticket doesn't look promising so we probably should just add ignores on these lines.
